# Generated by Django 3.2.5 on 2021-10-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0002_cus_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cus_signup',
        ),
    ]
