# Generated by Django 3.2.5 on 2021-10-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0004_cussignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cussignup',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='cussignup',
            name='password',
        ),
    ]
