# Generated by Django 3.2.5 on 2021-10-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0005_auto_20211015_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cussignin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
