# Generated by Django 3.2.5 on 2021-10-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0006_cussignin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cussignin',
            name='full_name',
        ),
    ]
