# Generated by Django 3.2.5 on 2021-10-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0008_rename_full_name_cussignup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cussignin',
            name='email',
        ),
    ]
