# Generated by Django 3.2.5 on 2021-10-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0009_remove_cussignin_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cussignin',
        ),
    ]
