# Generated by Django 3.2.5 on 2021-10-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0011_cussignin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cussignin',
        ),
    ]
