# Generated by Django 3.2.5 on 2021-10-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0013_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cussignup',
            new_name='Register',
        ),
    ]
