# Generated by Django 3.2.5 on 2021-10-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menuapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
