# Generated by Django 3.2.5 on 2021-11-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
