# Generated by Django 3.2.5 on 2021-12-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orderapp', '0003_booking_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='preferred_slot',
            new_name='preferred_time',
        ),
    ]
