# Generated by Django 3.2.5 on 2021-12-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orderapp', '0005_auto_20211207_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
