# Generated by Django 3.2.5 on 2021-12-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orderapp', '0007_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
