# Generated by Django 3.2.5 on 2021-12-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orderapp', '0011_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='login_as',
            new_name='booking_for',
        ),
    ]
