# Generated by Django 3.2.5 on 2022-01-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0013_auto_20220104_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commented_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_in', to='Blog_app.post'),
        ),
    ]
